<a href="https://colab.research.google.com/github/arnoldofr/matydet/blob/main/U2_ejemplos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.matrix([[2, 4],[1,3]])
A

matrix([[2, 4],
        [1, 3]])

In [ ]:
 B=np.matrix([[0,1],[2,3]])
B

matrix([[0, 1],
        [2, 3]])

In [ ]:
'Suma de matrices'
C=A+B
C

matrix([[2, 5],
        [3, 6]])

In [ ]:
'Multiplicacion de escalar por una matriz'
A=np.matrix([[1, -3],[3,1]])
A

matrix([[ 1, -3],
        [ 3,  1]])

In [ ]:
'Escalar' 
a=2
a

2

In [ ]:
C=a*A
C

matrix([[ 2, -6],
        [ 6,  2]])

In [ ]:
'Vector demanda por vector precio'
d=np.matrix([[30, 20, 40, 10]])
d

matrix([[30, 20, 40, 10]])

In [ ]:
 p=np.matrix([[20], [15], [18], [40]])
p

matrix([[20],
        [15],
        [18],
        [40]])

In [ ]:
'Venta = producto escalar de d y p'
V=d.dot(p)
V

matrix([[2020]])

In [ ]:
'Multiplicacion de matrices'
A=np.matrix([[1, 3],[-2,4]])
A

matrix([[ 1,  3],
        [-2,  4]])

In [ ]:
 B=np.matrix([[3, -2],[5,6]])
B

matrix([[ 3, -2],
        [ 5,  6]])

In [ ]:
C=A.dot(B)
C

matrix([[18, 16],
        [14, 28]])

In [ ]:
D=B.dot(A)
D

matrix([[ 7,  1],
        [-7, 39]])

In [ ]:
'Transformaciones elementales por renglon'
A=np.matrix([[1, 2],[2,3]])
A

matrix([[1, 2],
        [2, 3]])

In [ ]:
 b=np.matrix([[2],[6]])
b

matrix([[2],
        [6]])

In [ ]:
'Solucion'
C=np.linalg.solve(A,b)
C

matrix([[ 6.],
        [-2.]])

In [ ]:
'Rango de A'
D=np.linalg.matrix_rank(A)
D

2

In [ ]:
A=np.matrix([[1, 2],[2,4]])
A

matrix([[1, 2],
        [2, 4]])

In [ ]:
 'Rango de A'
D=np.linalg.matrix_rank(A)
D

1

In [ ]:
'Calculo de la inversa'
A=np.matrix([[1, 2],[2,3]])
A

matrix([[1, 2],
        [2, 3]])

In [ ]:
Ainv=np.linalg.inv(A)
Ainv

matrix([[-3.,  2.],
        [ 2., -1.]])

In [ ]:
'Determinante'
A=np.matrix([[2, 1],[4,3]])
A

matrix([[2, 1],
        [4, 3]])

In [ ]:
DetA=np.linalg.det(A)
DetA

2.0

In [ ]:
 B=np.matrix([[1,2,3],[5,7,8],[4,3,2]])
B

In [ ]:
 DetB=np.linalg.det(B)
DetB

In [ ]:
C=np.matrix([[5,7,8],[4,4,2],[1,2,3]])
C

In [ ]:
DetC=np.linalg.det(C)
DetC

In [ ]:
 DetBC=np.linalg.det(B.dot(C))
DetBC

# Sección nueva

In [ ]:
DetBC=np.linalg.det(B.dot(C))
DetBC

In [ ]:
%%html
<marquee><b>DetB</b></marquee>